'use client';

import React, { useState, useEffect } from 'react';
import { useAuth } from '@clerk/nextjs';
import api from '@/lib/api';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { Progress } from '@/components/ui/progress';
import {
  Shield,
  ShieldAlert,
  ShieldCheck,
  Play,
  Plus,
  Key,
  Lock,
  AlertTriangle,
  CheckCircle2,
  XCircle,
  Clock,
  Loader2,
  RefreshCw,
  Wand2,
  Sparkles,
  Brain,
  Eye,
} from 'lucide-react';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';

interface DetectedSensitiveData {
  type: string;
  description: string;
  examplePattern: string;
  riskLevel: 'low' | 'medium' | 'high' | 'critical';
  source: 'prompt' | 'knowledge_base';
  context: string;
}

interface LeakageScenario {
  id: string;
  name: string;
  description: string;
  is_builtin: boolean;
  isAutoGenerated?: boolean;
  sensitive_data: Array<{ type: string; value: string; pattern?: string; source?: string }>;
  conversation_flow: Array<{ role: string; template: string; expectedBehavior?: string }>;
  created_at: string;
}

interface LeakageTestRun {
  id: string;
  scenario_id: string;
  scenario_name?: string;
  status: 'passed' | 'failed' | 'warning';
  leakage_detected: boolean;
  leaked_items: Array<{ type: string; value: string; turnIndex: number; context: string }>;
  data_minimization_score: number;
  conversation_log: Array<{ role: string; content: string }>;
  run_at: string;
}

interface SecuritySummary {
  totalTests: number;
  passedTests: number;
  failedTests: number;
  warningTests: number;
  overallScore: number;
  lastTestDate: string | null;
  mostVulnerableTypes: Array<{ type: string; failures: number }>;
}

interface LeakageSecurityPanelProps {
  agentId: string;
}

export function LeakageSecurityPanel({ agentId }: LeakageSecurityPanelProps) {
  const { getToken } = useAuth();
  const [scenarios, setScenarios] = useState<LeakageScenario[]>([]);
  const [testRuns, setTestRuns] = useState<LeakageTestRun[]>([]);
  const [summary, setSummary] = useState<SecuritySummary | null>(null);
  const [detectedData, setDetectedData] = useState<DetectedSensitiveData[]>([]);
  const [loading, setLoading] = useState(true);
  const [runningTest, setRunningTest] = useState<string | null>(null);
  const [showCreateDialog, setShowCreateDialog] = useState(false);
  const [selectedRun, setSelectedRun] = useState<LeakageTestRun | null>(null);
  const [analyzing, setAnalyzing] = useState(false);
  const [generating, setGenerating] = useState(false);

  // Form state for new scenario
  const [newScenario, setNewScenario] = useState({
    name: '',
    description: '',
    sensitiveData: '',
    conversationFlow: '',
  });

  useEffect(() => {
    loadData();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [agentId]);

  const loadData = async () => {
    try {
      setLoading(true);
      const token = await getToken();
      const headers = { Authorization: `Bearer ${token}` };

      const [scenariosRes, runsRes, summaryRes] = await Promise.all([
        fetch(api.endpoints.leakageTests.scenarios(agentId), { headers }),
        fetch(api.endpoints.leakageTests.testRuns(agentId), { headers }),
        fetch(api.endpoints.leakageTests.securitySummary(agentId), { headers }),
      ]);

      if (scenariosRes.ok) {
        const data = await scenariosRes.json();
        setScenarios(data.scenarios || []);
      }
      if (runsRes.ok) {
        const data = await runsRes.json();
        setTestRuns(data.runs || []);
      }
      if (summaryRes.ok) {
        const data = await summaryRes.json();
        setSummary(data);
      }
    } catch (error) {
      console.error('Error loading security data:', error);
    } finally {
      setLoading(false);
    }
  };

  const runTest = async (scenarioId: string) => {
    try {
      setRunningTest(scenarioId);
      const token = await getToken();
      
      const res = await fetch(api.endpoints.leakageTests.runTest(agentId, scenarioId), {
        method: 'POST',
        headers: { Authorization: `Bearer ${token}` },
      });

      if (res.ok) {
        await loadData();
      }
    } catch (error) {
      console.error('Error running test:', error);
    } finally {
      setRunningTest(null);
    }
  };

  const createScenario = async () => {
    try {
      const token = await getToken();
      
      // Parse the JSON inputs
      let sensitiveData, conversationFlow;
      try {
        sensitiveData = JSON.parse(newScenario.sensitiveData);
        conversationFlow = JSON.parse(newScenario.conversationFlow);
      } catch {
        alert('Invalid JSON in sensitive data or conversation flow');
        return;
      }

      const res = await fetch(api.endpoints.leakageTests.createScenario(agentId), {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${token}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          name: newScenario.name,
          description: newScenario.description,
          sensitiveData,
          conversationFlow,
        }),
      });

      if (res.ok) {
        setShowCreateDialog(false);
        setNewScenario({ name: '', description: '', sensitiveData: '', conversationFlow: '' });
        await loadData();
      }
    } catch (error) {
      console.error('Error creating scenario:', error);
    }
  };

  // Analyze agent's prompt for sensitive data patterns
  const analyzeSensitiveData = async () => {
    try {
      setAnalyzing(true);
      const token = await getToken();
      
      const res = await fetch(`${api.endpoints.leakageTests.scenarios(agentId).replace('/leakage-scenarios', '/analyze-sensitive-data')}`, {
        method: 'POST',
        headers: { Authorization: `Bearer ${token}` },
      });

      if (res.ok) {
        const data = await res.json();
        setDetectedData(data.detectedSensitiveData || []);
      }
    } catch (error) {
      console.error('Error analyzing sensitive data:', error);
    } finally {
      setAnalyzing(false);
    }
  };

  // Auto-generate test scenarios based on agent's prompt
  const generateScenarios = async () => {
    try {
      setGenerating(true);
      const token = await getToken();
      
      const res = await fetch(`${api.endpoints.leakageTests.scenarios(agentId).replace('/leakage-scenarios', '/generate-leakage-scenarios')}`, {
        method: 'POST',
        headers: { Authorization: `Bearer ${token}` },
      });

      if (res.ok) {
        const data = await res.json();
        if (data.generatedScenarios?.length > 0) {
          await loadData();
        } else {
          alert(data.message || 'Could not generate scenarios. Add more details to the agent prompt.');
        }
      } else {
        const error = await res.json();
        alert(error.error || 'Failed to generate scenarios');
      }
    } catch (error) {
      console.error('Error generating scenarios:', error);
    } finally {
      setGenerating(false);
    }
  };

  const getStatusIcon = (status: string) => {
    switch (status) {
      case 'passed':
        return <CheckCircle2 className="h-4 w-4 text-green-500" />;
      case 'failed':
        return <XCircle className="h-4 w-4 text-red-500" />;
      case 'warning':
        return <AlertTriangle className="h-4 w-4 text-yellow-500" />;
      default:
        return <Clock className="h-4 w-4 text-gray-500" />;
    }
  };

  const getScoreColor = (score: number) => {
    if (score >= 90) return 'text-green-500';
    if (score >= 70) return 'text-yellow-500';
    return 'text-red-500';
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center p-12">
        <Loader2 className="h-8 w-8 animate-spin text-muted-foreground" />
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Summary Cards */}
      <div className="grid gap-4 md:grid-cols-4">
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Security Score</CardTitle>
            <Shield className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className={`text-2xl font-bold ${getScoreColor(summary?.overallScore || 0)}`}>
              {summary?.overallScore || 0}%
            </div>
            <Progress value={summary?.overallScore || 0} className="mt-2" />
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Tests Passed</CardTitle>
            <ShieldCheck className="h-4 w-4 text-green-500" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-green-600">
              {summary?.passedTests || 0}
            </div>
            <p className="text-xs text-muted-foreground">
              of {summary?.totalTests || 0} tests
            </p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Tests Failed</CardTitle>
            <ShieldAlert className="h-4 w-4 text-red-500" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-red-600">
              {summary?.failedTests || 0}
            </div>
            <p className="text-xs text-muted-foreground">
              leakage detected
            </p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Last Test</CardTitle>
            <Clock className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-sm font-medium">
              {summary?.lastTestDate 
                ? new Date(summary.lastTestDate).toLocaleDateString()
                : 'Never'}
            </div>
            <p className="text-xs text-muted-foreground">
              {summary?.warningTests || 0} warnings
            </p>
          </CardContent>
        </Card>
      </div>

      {/* Vulnerable Types Alert */}
      {summary?.mostVulnerableTypes && summary.mostVulnerableTypes.length > 0 && (
        <Alert variant="destructive">
          <AlertTriangle className="h-4 w-4" />
          <AlertTitle>Data Types at Risk</AlertTitle>
          <AlertDescription>
            The following data types showed leakage in tests:{' '}
            {summary.mostVulnerableTypes.map(t => t.type).join(', ')}
          </AlertDescription>
        </Alert>
      )}

      {/* Smart Auto-Generation Section */}
      <Card className="border-dashed border-2 bg-muted/30">
        <CardHeader>
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="p-2 bg-primary/10 rounded-lg">
                <Brain className="h-5 w-5 text-primary" />
              </div>
              <div>
                <CardTitle className="text-lg">Smart Leakage Detection</CardTitle>
                <CardDescription>
                  Auto-generate test scenarios based on your agent&apos;s prompt and knowledge base
                </CardDescription>
              </div>
            </div>
            <div className="flex gap-2">
              <Button 
                variant="outline" 
                size="sm" 
                onClick={analyzeSensitiveData}
                disabled={analyzing}
              >
                {analyzing ? (
                  <Loader2 className="h-4 w-4 animate-spin mr-2" />
                ) : (
                  <Eye className="h-4 w-4 mr-2" />
                )}
                Analyze Prompt
              </Button>
              <Button 
                size="sm" 
                onClick={generateScenarios}
                disabled={generating}
              >
                {generating ? (
                  <Loader2 className="h-4 w-4 animate-spin mr-2" />
                ) : (
                  <Wand2 className="h-4 w-4 mr-2" />
                )}
                Auto-Generate Tests
              </Button>
            </div>
          </div>
        </CardHeader>
        {detectedData.length > 0 && (
          <CardContent>
            <div className="space-y-3">
              <div className="text-sm font-medium flex items-center gap-2">
                <Sparkles className="h-4 w-4 text-yellow-500" />
                Detected Sensitive Data Categories
              </div>
              <div className="grid gap-2 md:grid-cols-2">
                {detectedData.map((item, idx) => (
                  <div key={idx} className="flex items-start gap-3 p-3 bg-background rounded-lg border">
                    <Badge 
                      variant={
                        item.riskLevel === 'critical' ? 'destructive' : 
                        item.riskLevel === 'high' ? 'destructive' : 
                        item.riskLevel === 'medium' ? 'default' : 'secondary'
                      }
                    >
                      {item.riskLevel}
                    </Badge>
                    <div className="flex-1 min-w-0">
                      <div className="font-medium text-sm">{item.type}</div>
                      <div className="text-xs text-muted-foreground truncate">
                        {item.description || item.context}
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </CardContent>
        )}
      </Card>

      <Tabs defaultValue="scenarios" className="space-y-4">
        <div className="flex items-center justify-between">
          <TabsList>
            <TabsTrigger value="scenarios">Test Scenarios</TabsTrigger>
            <TabsTrigger value="history">Test History</TabsTrigger>
          </TabsList>
          <div className="flex gap-2">
            <Button variant="outline" size="sm" onClick={loadData}>
              <RefreshCw className="h-4 w-4 mr-2" />
              Refresh
            </Button>
            <Dialog open={showCreateDialog} onOpenChange={setShowCreateDialog}>
              <DialogTrigger asChild>
                <Button size="sm" variant="outline">
                  <Plus className="h-4 w-4 mr-2" />
                  New Scenario
                </Button>
              </DialogTrigger>
              <DialogContent className="max-w-2xl">
                <DialogHeader>
                  <DialogTitle>Create Custom Leakage Test</DialogTitle>
                  <DialogDescription>
                    Define a custom scenario to test if your agent leaks sensitive data.
                  </DialogDescription>
                </DialogHeader>
                <div className="space-y-4 py-4">
                  <div className="space-y-2">
                    <Label htmlFor="name">Scenario Name</Label>
                    <Input
                      id="name"
                      value={newScenario.name}
                      onChange={(e) => setNewScenario(prev => ({ ...prev, name: e.target.value }))}
                      placeholder="e.g., API Key Leakage Test"
                    />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="description">Description</Label>
                    <Input
                      id="description"
                      value={newScenario.description}
                      onChange={(e) => setNewScenario(prev => ({ ...prev, description: e.target.value }))}
                      placeholder="Brief description of what this test checks"
                    />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="sensitiveData">Sensitive Data (JSON)</Label>
                    <Textarea
                      id="sensitiveData"
                      value={newScenario.sensitiveData}
                      onChange={(e) => setNewScenario(prev => ({ ...prev, sensitiveData: e.target.value }))}
                      placeholder={`[{"type": "api_key", "value": "sk-test-12345", "pattern": "sk-[a-z]+-[0-9]+"}]`}
                      rows={3}
                    />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="conversationFlow">Conversation Flow (JSON)</Label>
                    <Textarea
                      id="conversationFlow"
                      value={newScenario.conversationFlow}
                      onChange={(e) => setNewScenario(prev => ({ ...prev, conversationFlow: e.target.value }))}
                      placeholder={`[{"role": "user", "template": "I need to verify my API key is {{api_key}}"}]`}
                      rows={4}
                    />
                  </div>
                </div>
                <DialogFooter>
                  <Button variant="outline" onClick={() => setShowCreateDialog(false)}>Cancel</Button>
                  <Button onClick={createScenario}>Create Scenario</Button>
                </DialogFooter>
              </DialogContent>
            </Dialog>
          </div>
        </div>

        <TabsContent value="scenarios" className="space-y-4">
          {scenarios.length === 0 ? (
            <Card>
              <CardContent className="flex flex-col items-center justify-center py-12">
                <div className="p-4 bg-primary/10 rounded-full mb-4">
                  <Wand2 className="h-10 w-10 text-primary" />
                </div>
                <h3 className="text-lg font-medium">No Test Scenarios Yet</h3>
                <p className="text-sm text-muted-foreground mb-6 text-center max-w-md">
                  Use <strong>Auto-Generate Tests</strong> above to automatically create leakage test scenarios
                  based on your agent&apos;s prompt and knowledge base. No need to input sensitive data manually!
                </p>
                <div className="flex gap-3">
                  <Button variant="outline" onClick={() => setShowCreateDialog(true)}>
                    <Plus className="h-4 w-4 mr-2" />
                    Manual Create
                  </Button>
                  <Button onClick={generateScenarios} disabled={generating}>
                    {generating ? (
                      <Loader2 className="h-4 w-4 animate-spin mr-2" />
                    ) : (
                      <Wand2 className="h-4 w-4 mr-2" />
                    )}
                    Auto-Generate
                  </Button>
                </div>
              </CardContent>
            </Card>
          ) : (
            <div className="grid gap-4 md:grid-cols-2">
              {scenarios.map((scenario) => (
                <Card key={scenario.id}>
                  <CardHeader className="pb-2">
                    <div className="flex items-start justify-between">
                      <div>
                        <CardTitle className="text-base flex items-center gap-2">
                          <Shield className="h-4 w-4" />
                          {scenario.name}
                        </CardTitle>
                        <CardDescription className="mt-1">
                          {scenario.description}
                        </CardDescription>
                      </div>
                      <div className="flex gap-1">
                        {scenario.isAutoGenerated && (
                          <Badge variant="outline" className="text-xs">
                            <Sparkles className="h-3 w-3 mr-1" />
                            Auto
                          </Badge>
                        )}
                        {scenario.is_builtin && (
                          <Badge variant="secondary">Built-in</Badge>
                        )}
                      </div>
                    </div>
                  </CardHeader>
                  <CardContent>
                    <div className="flex items-center justify-between">
                      <div className="text-sm text-muted-foreground">
                        {scenario.sensitive_data?.length || 0} data types • {scenario.conversation_flow?.length || 0} turns
                      </div>
                      <Button
                        size="sm"
                        onClick={() => runTest(scenario.id)}
                        disabled={runningTest === scenario.id}
                      >
                        {runningTest === scenario.id ? (
                          <Loader2 className="h-4 w-4 animate-spin mr-2" />
                        ) : (
                          <Play className="h-4 w-4 mr-2" />
                        )}
                        Run Test
                      </Button>
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          )}
        </TabsContent>

        <TabsContent value="history" className="space-y-4">
          {testRuns.length === 0 ? (
            <Card>
              <CardContent className="flex flex-col items-center justify-center py-12">
                <Clock className="h-12 w-12 text-muted-foreground mb-4" />
                <h3 className="text-lg font-medium">No Test History</h3>
                <p className="text-sm text-muted-foreground">
                  Run some leakage tests to see results here.
                </p>
              </CardContent>
            </Card>
          ) : (
            <div className="space-y-3">
              {testRuns.map((run) => (
                <Card
                  key={run.id}
                  className="cursor-pointer hover:shadow-md transition-shadow"
                  onClick={() => setSelectedRun(selectedRun?.id === run.id ? null : run)}
                >
                  <CardContent className="py-4">
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-3">
                        {getStatusIcon(run.status)}
                        <div>
                          <div className="font-medium">{run.scenario_name || 'Leakage Test'}</div>
                          <div className="text-sm text-muted-foreground">
                            {new Date(run.run_at).toLocaleString()}
                          </div>
                        </div>
                      </div>
                      <div className="flex items-center gap-4">
                        <div className="text-right">
                          <div className={`text-sm font-medium ${getScoreColor(run.data_minimization_score)}`}>
                            {run.data_minimization_score}% minimization
                          </div>
                          <div className="text-xs text-muted-foreground">
                            {run.leaked_items?.length || 0} items leaked
                          </div>
                        </div>
                        <Badge variant={run.status === 'passed' ? 'default' : run.status === 'failed' ? 'destructive' : 'secondary'}>
                          {run.status}
                        </Badge>
                      </div>
                    </div>

                    {selectedRun?.id === run.id && (
                      <div className="mt-4 pt-4 border-t space-y-4">
                        {run.leaked_items && run.leaked_items.length > 0 && (
                          <div>
                            <h4 className="text-sm font-medium mb-2">Leaked Data</h4>
                            <div className="space-y-2">
                              {run.leaked_items.map((item, idx) => (
                                <div key={idx} className="flex items-center gap-2 text-sm bg-red-50 dark:bg-red-950 p-2 rounded">
                                  <AlertTriangle className="h-4 w-4 text-red-500" />
                                  <span className="font-medium">{item.type}:</span>
                                  <code className="text-red-600">{item.value}</code>
                                  <span className="text-muted-foreground">at turn {item.turnIndex + 1}</span>
                                </div>
                              ))}
                            </div>
                          </div>
                        )}

                        {run.conversation_log && run.conversation_log.length > 0 && (
                          <div>
                            <h4 className="text-sm font-medium mb-2">Conversation Log</h4>
                            <div className="space-y-2 max-h-48 overflow-y-auto">
                              {run.conversation_log.map((msg, idx) => (
                                <div
                                  key={idx}
                                  className={`p-2 rounded text-sm ${
                                    msg.role === 'user'
                                      ? 'bg-blue-50 dark:bg-blue-950 ml-4'
                                      : 'bg-gray-50 dark:bg-gray-900 mr-4'
                                  }`}
                                >
                                  <span className="font-medium">{msg.role}:</span> {msg.content}
                                </div>
                              ))}
                            </div>
                          </div>
                        )}
                      </div>
                    )}
                  </CardContent>
                </Card>
              ))}
            </div>
          )}
        </TabsContent>


      </Tabs>
    </div>
  );
}

// Compact badge for agent cards
export function LeakageSecurityBadge({ score }: { score: number }) {
  const getVariant = () => {
    if (score >= 90) return 'default';
    if (score >= 70) return 'secondary';
    return 'destructive';
  };

  return (
    <Badge variant={getVariant()} className="gap-1">
      <Shield className="h-3 w-3" />
      {score}%
    </Badge>
  );
}
